version: '3.1'

services:

  db:
    image: postgres:12
    volumes:
    - ./db:/var/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cook
      PGDATA: /var/data
    ports:
      - 5432:5432